# Generated by Django 5.0.2 on 2024-04-21 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('Create', 'create'), ('Read', 'read'), ('Update', 'update'), ('Delete', 'delete'), ('Login', 'login'), ('Logout', 'logout'), ('Login Failed', 'login failed')], max_length=15)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Success', 'success'), ('Failed', 'failed')], default='Success', max_length=7)),
                ('data', models.JSONField(default=dict)),
                ('object_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
